services:
  app:
    build: .
    container_name: langchain-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - langchain-network

networks:
  langchain-network:
    driver: bridge
